server:
  port: 8080

  spring:
    profiles:
      active: dev

redis:
  database: 0
  host: localhost
  password: 668827
  pool:
    max-active: 8
    max-idle: 8
    max-wait: -1
    min-idle: 0
  port: 6379
  timeout: 5000

spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leigexi?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: liuyinuo1314
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.lhrlyn.cn.lhrlynadmin.user.enity
  mapper-locations: "classpath*:mapper/**/*.xml"
logging:
  level:
    com:
      lhrlyn:
        cn:
          lhrlynadmin:
            user:
              mapper: debug
upload:
  imagePath: /Users/emlynchen/Pictures/leigexi
